{ config, lib, pkgs, ... }:
{
  boot = {
    # V Generated by nixos-generate-config V
    initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
    # ^------------------------------------^
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/23397b87-7a9f-4a85-ad20-215c4d8da652";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd:1" ];
    };

    "/nix" = {
      device = "/dev/disk/by-uuid/23397b87-7a9f-4a85-ad20-215c4d8da652";
      fsType = "btrfs";
      options = [ "subvol=@nix" "noatime" "compress=zstd:1" ];
    };

    "/home" = {
      device = "/dev/disk/by-uuid/23397b87-7a9f-4a85-ad20-215c4d8da652";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd:1" ];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/AC06-9081";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };
  };

  zramSwap.enable = true;

  systemModules = {
    common = {
      userName = "remedan";
      hostName = "rincewind";
      cpuType = "intel";
      desktopEnvironment = "KDE";
    };
    boot.luks = {
      enable = true;
      uuid = "4fe9e530-4428-4f07-a102-641e35f11155";
    };
  };
}
