{ config, lib, pkgs, modulesPath, ... }:
{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot = {
    # V Generated by nixos-generate-config V
    initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
    # ^------------------------------------^
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/7fbabfcb-2761-4580-a0bc-4320c331fa0e";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd:1" ];
    };

    "/nix" = {
      device = "/dev/disk/by-uuid/7fbabfcb-2761-4580-a0bc-4320c331fa0e";
      fsType = "btrfs";
      options = [ "subvol=@nix" "noatime" "compress=zstd:1" ];
    };

    "/home" = {
      device = "/dev/disk/by-uuid/7fbabfcb-2761-4580-a0bc-4320c331fa0e";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd:1" ];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/BBEA-C5C6";
      fsType = "vfat";
    };
  };

  zramSwap.enable = true;

  # Qemu guest integration
  services.qemuGuest.enable = true;
  services.spice-vdagentd.enable = true;

  systemModules = {
    base = {
      userName = "remedan";
      hostName = "nixos";
      cpuType = "amd";
    };
  };
}
