{ config, lib, pkgs, ... }:
{
  boot = {
    # V Generated by nixos-generate-config V
    initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
    # ^------------------------------------^
  };

  fileSystems =
    let
      cifsOptions = [
        "_netdev"
        "nofail"
        "vers=2.1"
        "credentials=/home/remedan/.smbcredentials"
        "uid=${toString config.users.users.remedan.uid}"
        "gid=${toString config.users.groups.remedan.gid}"
      ];
    in
    {
      "/" = {
        device = "/dev/disk/by-uuid/6fc090b5-66e2-4870-91f0-145d46b65f84";
        fsType = "btrfs";
        options = [ "subvol=@" "compress=zstd:1" ];
      };

      "/nix" = {
        device = "/dev/disk/by-uuid/6fc090b5-66e2-4870-91f0-145d46b65f84";
        fsType = "btrfs";
        options = [ "subvol=@nix" "noatime" "compress=zstd:1" ];
      };

      "/home" = {
        device = "/dev/disk/by-uuid/6fc090b5-66e2-4870-91f0-145d46b65f84";
        fsType = "btrfs";
        options = [ "subvol=@home" "compress=zstd:1" ];
      };

      "/boot" = {
        device = "/dev/disk/by-uuid/EE81-37E8";
        fsType = "vfat";
      };

      "/home/remedan/Network/home" = {
        device = "//192.168.4.3/homes/remedan";
        fsType = "cifs";
        options = cifsOptions;
      };

      "/home/remedan/Network/Media" = {
        device = "//192.168.4.3/Media";
        fsType = "cifs";
        options = cifsOptions;
      };
    };

  zramSwap.enable = true;

  # Fixes blutooth Xbox One controller issues
  hardware.xpadneo.enable = true;

  system-modules = {
    common = {
      userName = "remedan";
      hostName = "weatherwax";
      cpuType = "amd";
      desktopEnvironment = "KDE";
    };
    nvidia.enable = true;
  };
}
